// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQlUnlNCaxoCiFUTWbcHkoYlXCV6BsBg',
    appId: '1:668521501041:web:fac68d536e5df46e4366d0',
    messagingSenderId: '668521501041',
    projectId: 'pfe-project-61b68',
    authDomain: 'pfe-project-61b68.firebaseapp.com',
    storageBucket: 'pfe-project-61b68.appspot.com',
    measurementId: 'G-5MTYNZXRSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPJC42W21rJxeqhtr5KimT9YVN1K8ftPk',
    appId: '1:668521501041:android:6a64f72e78d5583c4366d0',
    messagingSenderId: '668521501041',
    projectId: 'pfe-project-61b68',
    storageBucket: 'pfe-project-61b68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVtxtKLxrYSOBTXA1wUtoTOVxk6HlkxI',
    appId: '1:668521501041:ios:4398791614b472704366d0',
    messagingSenderId: '668521501041',
    projectId: 'pfe-project-61b68',
    storageBucket: 'pfe-project-61b68.appspot.com',
    iosClientId: '668521501041-6ba2skvr3ald5on15kvg6r0st6ii580m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcVtxtKLxrYSOBTXA1wUtoTOVxk6HlkxI',
    appId: '1:668521501041:ios:4398791614b472704366d0',
    messagingSenderId: '668521501041',
    projectId: 'pfe-project-61b68',
    storageBucket: 'pfe-project-61b68.appspot.com',
    iosClientId: '668521501041-6ba2skvr3ald5on15kvg6r0st6ii580m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfe',
  );
}
